name: sql_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqfentity: ^2.4.0
  sqfentity_gen: ^2.3.0+4
  http: ^0.13.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  lottie: ^2.1.0
  image_picker: ^0.8.7+4
  image_cropper: ^3.0.3
  flutter_svg: ^2.0.5
  image: ^4.1.3
  dotted_border: ^2.0.0+3
  sqflite_sqlcipher: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  build_verify: ^3.1.0
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/lotties/
  - assets/icons/

  